const CARDS = 
[
  {
    "id": 1,
    "region": "🦴 CERVICAL",
    "num": "1",
    "name": "Rot. columna vertebral cervical",
    "category": "Movilidad cervical",
    "posPatient": "Sentado relajado, brazos paralelos al tronco, manos sobre rodillas.",
    "posTherapist": "De pie detrás (finta doble). Manos a ambos lados de la cabeza.",
    "execution": "Rotación pasiva máxima a izquierda y derecha sin forzar.",
    "interpretation": "✅ Tope seco + asimetría → alteración cervical (localización según momento del arco). ⚠️ Mareos/nistagmo → descartar causa vascular o vestibular."
  },
  {
    "id": 2,
    "region": "🦴 CERVICAL",
    "num": "2",
    "name": "Rot. cabeza en extensión máxima",
    "category": "Movilidad cervical",
    "posPatient": "Sentado relajado, brazos a lo largo del tronco, manos sobre piernas.",
    "posTherapist": "De pie lateral (finta doble). Mano posterior en occipucio; mano anterior en mentón.",
    "execution": "1. Extensión pasiva cervical máxima (bloquea segmento cervical alto).\n2. Manteniendo extensión → rotación a cada lado.\n(La rotación se realiza solo con cervical baja, zona cervicotorácica y dorsal alta.)",
    "interpretation": "✅ Dolor + limitación en rotación con cuello en extensión → artrosis/degeneración cervical media-baja o torácica alta."
  },
  {
    "id": 3,
    "region": "🦴 CERVICAL",
    "num": "3",
    "name": "Rot. cabeza en flexión máxima",
    "category": "Movilidad cervical",
    "posPatient": "Sentado relajado, brazos a lo largo del tronco, manos sobre piernas.",
    "posTherapist": "De pie lateral (finta doble). Mano posterior en occipucio; mano anterior en mentón.",
    "execution": "1. Flexión pasiva cervical máxima (bloquea segmento cervical por debajo de D2).\n2. Manteniendo flexión → rotación a cada lado.\n(Rotación solo con cervical alta: occipucio, atlas, axis.)",
    "interpretation": "✅ Dolor + limitación en rotación con cuello en flexión → alteración degenerativa cervical alta (occipucio, atlas, axis)."
  },
  {
    "id": 4,
    "region": "🦴 CERVICAL",
    "num": "4",
    "name": "Prueba de distracción cervical",
    "category": "Inestabilidad ligamentosa",
    "posPatient": "Sentado, brazos extendidos a lo largo del tronco, manos sobre muslos, cabeza en posición neutra.\n⚠️ Contraindicada en inestabilidad importante de columna cervical.",
    "posTherapist": "De pie lateral (finta doble). Mano posterior bajo occipucio; mano anterior bajo mandíbula.",
    "execution": "Tracción axial lenta y progresiva hacia el techo de la cabeza del paciente.",
    "interpretation": "✅ Dolor desaparece → atrapamiento radicular. ✅ Dolor aumenta → afectación capsuloligamentosa o musculatura monoarticular."
  },
  {
    "id": 5,
    "region": "🦴 CERVICAL",
    "num": "5",
    "name": "Prueba de Sharp-Purser",
    "category": "Inestabilidad ligamentosa",
    "posPatient": "Sedestación, brazos extendidos paralelos al cuerpo, cabeza en posición neutra con cuello en ligera flexión.",
    "posTherapist": "De pie lateral (finta doble), cabeza del paciente a la altura de su pecho. Mano anterior en frontal; mano posterior en occipucio.",
    "execution": "Con la mano anterior → deslizamiento anteroposterior del frontal.\nEsto impone movimiento del occipucio respecto al atlas y del atlas respecto al axis.",
    "interpretation": "✅ Dolor en región cervical → posible inestabilidad atlantoaxial ligamentosa. ⚠️ Test muy inespecífico."
  },
  {
    "id": 6,
    "region": "🦴 CERVICAL",
    "num": "6",
    "name": "Prueba de percusión de apófisis",
    "category": "Inestabilidad ligamentosa",
    "posPatient": "Sentado, brazos paralelos al tronco, manos sobre muslos.",
    "posTherapist": "De pie lateral (finta doble). Mano anterior sobre frontal (codo estabiliza hombro homolateral); mano posterior libre.",
    "execution": "1. Ligera flexión pasiva de la columna cervical.\n2. Con la mano posterior → percutir con dedos las apófisis espinosas cervicales.",
    "interpretation": "✅ Dolor localizado → fractura/afectación ligamentosa o muscular. ✅ Dolor radicular → afectación de raíces nerviosas."
  },
  {
    "id": 7,
    "region": "🦴 CERVICAL",
    "num": "7",
    "name": "Prueba de Jackson (compresión cervical)",
    "category": "Patología discal cervical",
    "posPatient": "Sedestación, brazos extendidos, manos sobre muslos, mirando al frente.",
    "posTherapist": "Bipedestación detrás del paciente (finta doble). Dedos de ambas manos entrelazados sobre la parte superior de la cabeza; codos estabilizan hombros del paciente.",
    "execution": "Compresión axial descendente y progresiva sobre la cabeza.",
    "interpretation": "✅ Dolor cervical con irradiación al brazo → afectación discal o facetaria. ⚡ Sin irradiación → descarta patología discal cervical."
  },
  {
    "id": 8,
    "region": "🦴 CERVICAL",
    "num": "8",
    "name": "Prueba de Spurling (compresión foraminal)",
    "category": "Patología discal cervical",
    "posPatient": "Sentado, brazos a lo largo del cuerpo, manos sobre muslos, cabeza en posición neutra. Paciente RELAJADO.\n⚠️ Precaución en osteoporosis grave o tumores.",
    "posTherapist": "De pie detrás del paciente (finta doble). Una mano plana sobre la parte superior de la cabeza.",
    "execution": "Se realiza en 3 posiciones (según Bradley):\n1. POSICIÓN NEUTRA: golpe seco suave con el puño sobre la mano en el vértex.\n2. EXTENSIÓN cervical: igual.\n3. EXTENSIÓN + ROTACIÓN homolateral: igual.\nCada posición provoca un cierre foraminal progresivo.",
    "interpretation": "✅ Aumento de síntomas → afectación discal o hernia cervical. Distribución del dolor orienta hacia la raíz afectada."
  },
  {
    "id": 9,
    "region": "🦴 CERVICAL",
    "num": "9",
    "name": "Test de abducción del hombro",
    "category": "Patología discal cervical",
    "posPatient": "Paciente coloca activamente la mano/brazo afectado sobre la cabeza (abducción).",
    "posTherapist": "Observación.",
    "execution": "Paciente eleva el brazo afectado y coloca la mano sobre la cabeza de forma activa.",
    "interpretation": "✅ Alivio o cese de síntomas → compatible con radiculopatía cervical."
  },
  {
    "id": 10,
    "region": "🦴 CERVICAL",
    "num": "10",
    "name": "Compresión máx. agujero intervertebral",
    "category": "Problema facetario cervical",
    "posPatient": "Sentado, brazos a lo largo del tronco, manos sobre muslos.",
    "posTherapist": "De pie, observando al paciente.",
    "execution": "El paciente realiza ACTIVAMENTE:\nRotación + inclinación lateral del mismo lado + extensión cervical.\n→ Esto implica cierre máximo del agujero de conjunción homolateral.",
    "interpretation": "✅ Dolor local homolateral → imbricación de carillas. ✅ Dolor contralateral → afectación muscular. ✅ Dolor radicular → afectación de raíces nerviosas."
  },
  {
    "id": 11,
    "region": "🫁 TORÁCICA",
    "num": "11",
    "name": "Test movilidad segmentaria posteroanterior",
    "category": "Movilidad segmentaria dorsal",
    "posPatient": "Decúbito prono sobre la camilla.",
    "posTherapist": "De pie lateral al paciente.",
    "execution": "Terapeuta aplica presión posteroanterior sobre las apófisis espinosas o costillas dorsales, segmento por segmento, con las manos.",
    "interpretation": "✅ Rigidez o dolor localizado → hipomobilidad segmentaria dorsal. ✅ Hipermobilidad → posible inestabilidad."
  },
  {
    "id": 12,
    "region": "🫁 TORÁCICA",
    "num": "12",
    "name": "Prueba de compresión de costillas",
    "category": "Posible fractura / fisura costal",
    "posPatient": "Sentado, brazos relajados paralelos al tronco, manos sobre muslos.",
    "posTherapist": "De pie detrás del paciente (finta doble). Pasa sus brazos rodeando el tórax y abdomen del paciente por los huecos formados por los brazos; dedos entrelazados en parte anterior del tórax.",
    "execution": "Compresión ANTEROPOSTERIOR y LATERAL con ambos brazos simultáneamente.",
    "interpretation": "✅ Dolor local → restricción costal. ✅ Dolor radicular → neuralgia intercostal. ✅ No aguanta la prueba → posible fractura/fisura costal."
  },
  {
    "id": 13,
    "region": "🫁 TORÁCICA",
    "num": "13",
    "name": "Signo de Shepelman",
    "category": "Neuropatía / Radiculopatía dorsal",
    "posPatient": "Sedestación, brazos paralelos al tronco, manos reposadas sobre la camilla.",
    "posTherapist": "Bipedestación detrás del paciente (finta doble).",
    "execution": "Terapeuta solicita al paciente que incline el cuerpo hacia un lado y luego al otro de forma alternativa (lateroflexión activa del tronco).",
    "interpretation": "✅ Dolor en el lado de la inclinación → neuralgia intercostal. ✅ Dolor en el lado contrario → signo de pleuritis."
  },
  {
    "id": 14,
    "region": "🫁 TORÁCICA",
    "num": "14",
    "name": "Signo de Adam",
    "category": "Valorar escoliosis",
    "posPatient": "Bipedestación, brazos a lo largo del tronco.",
    "posTherapist": "Detrás del paciente, observando.",
    "execution": "Paciente realiza:\n1. Flexión cervical máxima.\n2. Flexión de tronco ~90°.\n3. Brazos colgando de forma relajada.",
    "interpretation": "✅ Abombamiento en hemitórax → escoliosis estructural. ✅ Curvatura desaparece con la flexión → escoliosis funcional."
  },
  {
    "id": 15,
    "region": "🦵 LUMBAR",
    "num": "15",
    "name": "Signo de Hoover (test comportamiento)",
    "category": "Movilidad lumbar / Simulación",
    "posPatient": "Decúbito supino, brazos extendidos, rodillas en extensión, piernas relajadas sobre camilla.",
    "posTherapist": "De pie lateral (finta adelante hacia la cabeza). Mano caudal bajo talón; mano craneal a altura de rodilla para fijar extensión.",
    "execution": "Pedir al paciente que levante la pierna NO fijada con rodilla en extensión. Terapeuta sujeta la otra pierna. Realizar en ambas piernas.",
    "interpretation": "✅ Refiere no poder levantar la pierna pero sin presión en el calcáneo contralateral → simulación."
  },
  {
    "id": 16,
    "region": "🦵 LUMBAR",
    "num": "16",
    "name": "Prueba de Schober",
    "category": "Movilidad lumbar",
    "posPatient": "De pie, brazos a lo largo del tronco.",
    "posTherapist": "De pie a un lado del paciente (finta doble).",
    "execution": "1. Con rotulador: marca horizontal a nivel S1 y otra 10 cm por encima.\n2. Pedir que se incline hacia delante → medir distancia entre marcas.\n3. Pedir que se extienda → medir nuevamente.",
    "interpretation": "✅ Separación <15 cm en flexión o <8-9 cm en extensión → limitación de la elasticidad lumbar. Útil en espondilitis anquilosante."
  },
  {
    "id": 17,
    "region": "🦵 LUMBAR",
    "num": "17",
    "name": "Prueba de distancia dedo-suelo",
    "category": "Movilidad lumbar",
    "posPatient": "Bipedestación, pies juntos, rodillas completamente extendidas.",
    "posTherapist": "A un lado del paciente en cuclillas con cinta métrica.",
    "execution": "Paciente realiza anteflexión activa de columna (brazos, manos y dedos extendidos y relajados hacia delante):\n1. Flexión de caderas bilateralmente.\n2. Flexión del raquis lumbar (sobre todo L5-S1).\n3. Retroversión de pelvis.\nMedir distancia entre la punta de los dedos y el suelo.",
    "interpretation": "✅ Dolor al inicio → restricción coxofemoral. ✅ Dolor en 2ª parte → disfunción lumbar o sacroilíaca. ✅ Dolor en 3ª parte → lumbar alta o torácica."
  },
  {
    "id": 18,
    "region": "🦵 LUMBAR",
    "num": "18",
    "name": "Test de Valsalva",
    "category": "Patología discal lumbar",
    "posPatient": "Sedestación, brazos a lo largo del cuerpo, manos sobre muslos.\n⚠️ Contraindicado en glaucoma (aumenta presión intracraneal).",
    "posTherapist": "Bipedestación junto al paciente.",
    "execution": "Paciente: inspiración máxima → espiración forzada máxima SIN expulsar el aire (como para defecar).",
    "interpretation": "✅ Dolor o aumento del dolor raquídeo → afectación discal con posible hernia. ✅ Dolor en ligamento inguinal → posible hernia inguinal."
  },
  {
    "id": 19,
    "region": "🦵 LUMBAR",
    "num": "19",
    "name": "Signo de Bonnet",
    "category": "Neuropatía / Radiculopatía lumbar",
    "posPatient": "Decúbito dorsal, MMSS a lo largo del cuerpo. Pierna a valorar: rodilla en flexión, planta del pie apoyada en camilla. Pierna contraria: extensión de rodilla.",
    "posTherapist": "De pie en el lado a valorar (finta doble), altura de caderas. Mano craneal sobre rodilla homolateral; mano caudal abarca el empeine del mismo pie.",
    "execution": "Terapeuta realiza APROXIMACIÓN + ROTACIÓN INTERNA de la cadera del lado a evaluar.",
    "interpretation": "✅ Dolor y/o parestesias en recorrido ciático → compresión del nervio ciático a nivel del músculo piramidal."
  },
  {
    "id": 20,
    "region": "🦵 LUMBAR",
    "num": "20",
    "name": "Estiramiento nervio femoral",
    "category": "Neuropatía / Radiculopatía lumbar",
    "posPatient": "Decúbito ventral, brazos a lo largo del cuerpo, piernas sobre camilla con rodillas en extensión.",
    "posTherapist": "Bipedestación en el lado a valorar (finta adelante en dirección craneal) a la altura de las rodillas del paciente.",
    "execution": "1. Flexionar rodilla del paciente ~90°.\n2. Mano caudal sobre cara anterior de rodilla homolateral.\n3. Mano craneal abarca el pie.\n4. Contactar el pecho con la cara anterior de la tibia del lado a valorar.\n5. Dejarse caer lentamente → inducir flexión de rodilla + extensión de cadera.",
    "interpretation": "✅ Dolor lumbar o en recorrido del nervio femoral → compresión del nervio femoral."
  },
  {
    "id": 21,
    "region": "🦵 LUMBAR",
    "num": "21",
    "name": "Prueba de Lasègue (SLR)",
    "category": "Neuropatía / Radiculopatía lumbar",
    "posPatient": "Decúbito supino, brazos a lo largo del cuerpo, rodillas extendidas.",
    "posTherapist": "Bipedestación lateral (finta doble) a la altura de las tibias. Mano craneal en cara anterolateral de la pierna SANA algo por encima de la rodilla (mantiene extensión); mano caudal en calcáneo del mismo lado.",
    "execution": "Terapeuta flexiona pasivamente la cadera SANA del paciente manteniendo la rodilla en extensión. La otra pierna queda en reposo sobre la camilla.\n💡 Se aplica estiramiento dural en ambos lados → puede aparecer dolor radicular también en pierna contra la camilla.",
    "interpretation": "✅ Dolor lumbar o ciático durante la maniobra → afectación discal lumbar."
  },
  {
    "id": 22,
    "region": "🦵 LUMBAR",
    "num": "22",
    "name": "Signo de Bragard",
    "category": "Neuropatía / Radiculopatía lumbar",
    "posPatient": "Decúbito supino (igual que Lasègue).",
    "posTherapist": "Igual que Lasègue.",
    "execution": "1. Realizar Lasègue hasta el punto donde aparece el dolor.\n2. Bajar ligeramente el miembro (reducir la tensión).\n3. Realizar DORSIFLEXIÓN del pie.",
    "interpretation": "✅ Reaparece el dolor con la dorsiflexión → confirma origen neural (complementa el Lasègue)."
  },
  {
    "id": 23,
    "region": "🦵 LUMBAR",
    "num": "23",
    "name": "Prueba de Thomas (Psoas)",
    "category": "Problema muscular lumbar",
    "posPatient": "Decúbito supino. Paciente lleva AMBAS rodillas al pecho con sus manos, fijándolas en esa posición.",
    "posTherapist": "De pie lateral al paciente (finta adelante), altura de caderas. Mano craneal bajo columna lumbar; mano caudal abarca el tercio distal de la tibia del lado a evaluar.",
    "execution": "Terapeuta baja lentamente hacia la extensión la pierna del lado cuyo músculo psoas quiere examinar. Examinar ambas piernas de forma alternativa.",
    "interpretation": "✅ Al extender la cadera aumenta la lordosis lumbar o no puede extender completamente → retracción/acortamiento del psoas."
  },
  {
    "id": 24,
    "region": "🦵 LUMBAR",
    "num": "24",
    "name": "Prueba del psoas",
    "category": "Problema muscular lumbar",
    "posPatient": "Decúbito supino, piernas en extensión de rodillas, brazos a lo largo del tronco reposados sobre la camilla.",
    "posTherapist": "Bipedestación lateral en el lado a valorar (finta doble), a la altura de las rodillas del paciente, orientado hacia este.",
    "execution": "1. Pedir al paciente que eleve la pierna SIN flexionar la rodilla.\n2. Aproximadamente a mitad del recorrido articular → terapeuta realiza una presión inesperada y súbita sobre la zona anterior del muslo llevándolo a extensión de cadera.",
    "interpretation": "✅ Dolor lumbar, sacroilíaco o coxofemoral → afectación lumbar o pélvica (espondiloartrosis, espondilitis o hernia discal)."
  },
  {
    "id": 25,
    "region": "🦵 LUMBAR",
    "num": "25",
    "name": "Test de Biering-Sorensen",
    "category": "Problema muscular lumbar",
    "posPatient": "Decúbito prono. Parte inferior del cuerpo apoyada en camilla y parte superior SUSPENDIDA horizontalmente. Brazos cruzados, manos en hombros. Borde de la camilla ≈ a nivel EIAS. Miembros inferiores fijados con cinchas a tobillos, rodillas y caderas.",
    "posTherapist": "Observando.",
    "execution": "Paciente mantiene el tronco en posición HORIZONTAL el mayor tiempo posible.\nSe da por finalizada cuando el paciente contacta con cualquier parte del tren superior en el suelo.",
    "interpretation": "✅ Tiempo de resistencia reducido → debilidad de la musculatura extensora lumbar, factor de riesgo de lumbalgia."
  },
  {
    "id": 26,
    "region": "🦴 CADERA",
    "num": "43",
    "name": "Prueba de Laguerre",
    "category": "Movilidad cadera / Disfunción sacroilíaca",
    "posPatient": "Decúbito dorsal, MMSS a lo largo del cuerpo, rodillas en extensión sobre la camilla.",
    "posTherapist": "Bipedestación en finta doble en el lado a valorar, a la altura de las tibias del paciente, orientado hacia este.",
    "execution": "1. Mano superior sobre la articulación de la rodilla homolateral.\n2. Mano inferior abarca el calcáneo de la pierna a valorar.\n3. Llevar la cadera y la rodilla a 90° de flexión cada una.\n4. Desde ahí, conducir de forma pasiva la cadera a separación y rotación externa, acercando el calcáneo a la línea media del cuerpo.",
    "interpretation": "✅ Dolor con la palpación de apófisis espinosas → disfunción sacroilíaca (comparar ambos lados)."
  },
  {
    "id": 27,
    "region": "🦴 CADERA",
    "num": "44",
    "name": "Test de compresión sacroilíaco",
    "category": "Movilidad cadera / Disfunción sacroilíaca",
    "posPatient": "La prueba comprende 4 posiciones (por orden):\n1. Decúbito dorsal, brazos a lo largo del cuerpo, rodillas extendidas.\n2. Tumbado de lado, miembro a valorar arriba con rodilla en extensión y miembro contralateral en flexión de cadera y rodilla sobre la camilla.\n3. Decúbito dorsal, brazos a lo largo, rodillas extendidas.\n4. Decúbito ventral, brazos a lo largo, rodillas extendidas.",
    "posTherapist": "4 posiciones del terapeuta correspondientes:\n1. Bipedestación a un lado, finta craneal. Talón de mano derecha sobre EIAS derecha y mano izquierda sobre EIAS izquierda (brazos cruzados).\n2. Bipedestación por delante del paciente (finta doble). Ambas manos sobre el hueso ilíaco a valorar en su parte externa.\n3. Bipedestación a un lado, finta craneal. Manos sobre crestas ilíacas por su borde externo.\n4. Bipedestación a la altura de la pelvis (finta craneal). Mano inferior encima del sacro; mano superior refuerza.",
    "execution": "4 empujes correspondientes a cada posición:\n1. Empuje hacia la camilla como para ABRIR los huesos ilíacos.\n2. Empuje hacia la camilla COMPRIMIENDO el hueso ilíaco.\n3. Empuje intentando UNIR ambas manos (cerrar los huesos ilíacos).\n4. Empuje COMPRIMIENDO el sacro hacia la camilla.",
    "interpretation": "✅ Cada empuje positivo orienta hacia la afectación de ligamentos sacroilíacos anteriores o posteriores según la dirección."
  },
  {
    "id": 28,
    "region": "🦴 CADERA",
    "num": "45",
    "name": "Test de Patrick / FABER",
    "category": "Movilidad cadera / Disfunción sacroilíaca",
    "posPatient": "Decúbito dorsal, MMSS a lo largo del tronco. El miembro del lado a valorar en flexión de rodilla de 90° y en abducción de cadera, de forma que la planta del pie contacte con la cara interna de la rodilla de la otra pierna (que reposa en extensión).",
    "posTherapist": "De pie en el lado a valorar, finta adelante en dirección craneal, a la altura de las rodillas del paciente. Mano interna contacta con la espina ilíaca anterosuperior de la hemipelvis CONTRALATERAL para bloquearla. Mano externa sobre cara interna de la rodilla del miembro a valorar.",
    "execution": "El terapeuta pide al paciente que lleve de forma activa el miembro del lado a valorar a abducción de cadera (rodilla hacia la camilla). Cuando ya no pueda más o la rodilla contacte la camilla → el terapeuta ejerce un poco de presión sobre ella hacia el suelo. Medir y contabilizar la distancia entre la rodilla del lado afecto y la camilla. Realizar en el miembro contralateral.",
    "interpretation": "✅ Mayor distancia rodilla-camilla + dolor → disfunción de cadera o articulación sacroilíaca."
  },
  {
    "id": 29,
    "region": "🦴 CADERA",
    "num": "46",
    "name": "Prueba de Ober",
    "category": "Cintilla iliotibial (BIT)",
    "posPatient": "Decúbito lateral con la cadera INFERIOR en flexión.",
    "posTherapist": "Detrás del paciente con una mano estabilizando la hemipelvis a testar.",
    "execution": "1. Mano proximal estabiliza la pelvis.\n2. Mano caudal realiza extensión de rodilla y extensión de cadera del muslo superior (la pierna queda libre).\n3. La pierna libre (superior) se deja caer por acción de la gravedad para que aduzca la cadera tanto como sea posible hasta contactar la camilla.",
    "interpretation": "✅ La rodilla no contacta la camilla → acortamiento de la banda iliotibial."
  },
  {
    "id": 30,
    "region": "🦴 CADERA",
    "num": "47",
    "name": "Signo de Trendelenburg",
    "category": "Musculatura pélvica",
    "posPatient": "De pie, MMSS a lo largo del cuerpo.",
    "posTherapist": "De pie a la espalda del paciente, observándolo.",
    "execution": "El terapeuta pide al paciente que separe un pie del suelo mediante flexión de la articulación coxofemoral y de la rodilla del mismo lado → apoyo monopodal. Observar la postura adoptada. Repetir en el miembro contralateral.",
    "interpretation": "✅ Hemipelvis contralateral descendida en apoyo monopodal → afectación de la musculatura pélvica (glúteo medio)."
  },
  {
    "id": 31,
    "region": "🦴 CADERA",
    "num": "48",
    "name": "Prueba de piriforme / rotadores",
    "category": "Musculatura pélvica",
    "posPatient": "Decúbito ventral con flexión de 70-80° de ambas rodillas, de forma que las plantas de los pies se encuentren orientadas hacia el techo.",
    "posTherapist": "Bipedestación próximo al borde inferior de la camilla en finta doble, orientado hacia la cabeza del paciente. Toma contacto con la palma de las manos sobre la región interna de cada uno de los dos pies.",
    "execution": "El paciente ha de mantener unidas ambas rodillas mientras el terapeuta ejerce una fuerza de separación de los tobillos.",
    "interpretation": "✅ Dolor glúteo y/o en recorrido ciático → posible espasmo o retracción del músculo piramidal con compresión del nervio ciático."
  },
  {
    "id": 32,
    "region": "🦴 CADERA",
    "num": "49",
    "name": "Test de Squeeze",
    "category": "Musculatura pélvica (aductores)",
    "posPatient": "Decúbito supino con las piernas flexionadas bilateralmente de forma que los pies queden apoyados en el plano de la camilla.",
    "posTherapist": "De pie, lateralmente al paciente del lado a valorar. Coloca el PUÑO entre las rodillas del paciente.",
    "execution": "Se pide al paciente que contraiga bilateralmente la musculatura APROXIMADORA de la cadera uniendo las rodillas contra el puño del terapeuta.",
    "interpretation": "✅ Dolor durante la contracción aproximadora → lesión tendinosa de los aductores de cadera."
  },
  {
    "id": 33,
    "region": "🦴 CADERA",
    "num": "50",
    "name": "Prueba de Galeazzi-Allis",
    "category": "Asimetría de MMII",
    "posPatient": "Decúbito dorsal, brazos a lo largo del cuerpo, rodillas y caderas flexionadas de forma que las plantas de los pies estén en contacto con la camilla.",
    "posTherapist": "De pie, observando al paciente desde los pies.",
    "execution": "Observar la altura de las rodillas comparando ambos lados: se valora si existe diferencia de altura entre las dos rodillas en la misma posición.",
    "interpretation": "✅ Una rodilla más alta → tibia más larga. ✅ Una rodilla más baja → fémur más corto o displasia/luxación de cadera."
  },
  {
    "id": 34,
    "region": "🦴 CADERA",
    "num": "51",
    "name": "FADIR – Femoroacetabular impingement test",
    "category": "Impingement femoroacetabular",
    "posPatient": "Decúbito supino con las piernas estiradas y los brazos a lo largo del cuerpo.",
    "posTherapist": "De pie, lateralmente al paciente del lado a valorar, a la altura de la pelvis. Mano caudal a la altura del tobillo; mano proximal en cara externa de la rodilla del paciente.",
    "execution": "1. Flexión pasiva de cadera y rodilla a 90°.\n2. Desde ahí → aducción de cadera + rotación interna asociada a un valgo de rodilla.",
    "interpretation": "✅ Dolor inguinal → posible pinzamiento femoroacetabular, desgarro del labrum, cuerpos libres o lesión condral."
  },
  {
    "id": 35,
    "region": "🦵 RODILLA",
    "num": "52",
    "name": "Prueba de McMurray",
    "category": "Meniscopatías",
    "posPatient": "Decúbito dorsal con el miembro del lado a valorar en flexión coxofemoral y de rodilla, de forma que la planta del pie se encuentre apoyada sobre la camilla.",
    "posTherapist": "De pie, en el mismo lado de la pierna a evaluar, a la altura de las rodillas, en finta adelante en dirección craneal. Mano superior sobre la articulación de la rodilla en la interlínea articular EXTERNA. Mano inferior abarca el talón del pie homolateral por la zona interna, de forma que el borde medial del pie esté en contacto con el antebrazo del terapeuta.",
    "execution": "El terapeuta eleva la pierna del lado a valorar separando el talón de la camilla. Según el cuerno y menisco a valorar:\n• Cuerno posterior menisco INTERNO: desde flexión máxima → rotación externa de tibia + valgo de rodilla + extensión.\n• Cuerno posterior menisco EXTERNO: desde flexión máxima → rotación interna de tibia + varo de rodilla + extensión.\n⚠️ Hay que corroborar el resultado con otras pruebas.",
    "interpretation": "✅ Dolor o chasquido en la interlínea articular → posible lesión meniscal (cuerno según rotación aplicada)."
  },
  {
    "id": 36,
    "region": "🦵 RODILLA",
    "num": "53",
    "name": "Test de compresión de Apley",
    "category": "Meniscopatías",
    "posPatient": "Decúbito ventral con la rodilla del lado a valorar en flexión de 90°, de forma que la planta del pie homolateral esté orientada hacia el techo.",
    "posTherapist": "De pie, en el mismo lado de la rodilla que se valora, en finta doble a la altura de esta, orientado hacia el paciente. Mano inferior sobre la planta del pie del lado a evaluar. Mano superior sobre la porción posterior del tercio distal del muslo homolateral, bloqueándolo.",
    "execution": "A través del contacto de la mano caudal → rotación de la rodilla a un lado y hacia el otro.\nActo seguido: compresión hacia la camilla con mano caudal + sin modificar la compresión → rotaciones internas y externas de la tibia.\n💡 Variante en extensión de rodilla para valorar mejor los cuernos anteriores.\n⚠️ Realizar primero sin compresión (distracción) para descartar ligamentos.",
    "interpretation": "✅ Dolor sin compresión → estructuras ligamentosas. ✅ Dolor con compresión → posible lesión meniscal (cuerno según rotación)."
  },
  {
    "id": 37,
    "region": "🦵 RODILLA",
    "num": "54",
    "name": "Glide test (desplazamiento de la rótula)",
    "category": "Movilidad rotuliana / Condropatía rotuliana",
    "posPatient": "Decúbito supino, brazos a lo largo del cuerpo, un rulo bajo las rodillas que se encuentran relajadas en ligera flexión.",
    "posTherapist": "De pie en el lado CONTRARIO a la pierna a evaluar, en finta doble a la altura de las rodillas del paciente, orientado hacia este. Toma contacto con el 1.er y 2.o dedos de ambas manos sobre los dos polos superior e inferior de la rótula del lado a valorar, abarcándola.",
    "execution": "Movilización de la rótula de un lateral a otro.\nSi durante la maniobra se observa elasticidad importante → puede solicitarse contracción isométrica del cuádriceps y repetir los desplazamientos.",
    "interpretation": "✅ Molestia y chasquido articular → condropatía rotuliana. ✅ Desplazamiento amplio → posible inestabilidad/luxación de rótula."
  },
  {
    "id": 38,
    "region": "🦵 RODILLA",
    "num": "55",
    "name": "Prueba de aprehensión (rótula)",
    "category": "Movilidad rotuliana / Inestabilidad rotuliana",
    "posPatient": "Decúbito supino.",
    "posTherapist": "De pie junto a la rodilla del paciente.",
    "execution": "1. Terapeuta desliza la rótula hacia EXTERNO.\n2. A partir de ahí → produce una flexión de rodilla.\n3. El paciente evitará el movimiento y apartará la mano del fisioterapeuta ante la sensación de luxación.",
    "interpretation": "✅ Aprehensión o retirada de la mano → inestabilidad rotuliana con tendencia a la luxación."
  },
  {
    "id": 39,
    "region": "🦵 RODILLA",
    "num": "56",
    "name": "Signo de Clarke (opresión/crepitación rotuliana)",
    "category": "Movilidad rotuliana / Articulación femoropatelar",
    "posPatient": "Decúbito dorsal, MMSS a lo largo del cuerpo, rodillas en extensión.",
    "posTherapist": "Bipedestación del lado a valorar en finta doble, a la altura de las rodillas, orientado hacia el paciente. Mano craneal sobre el margen superior de la rótula del lado a evaluar (comisura 1.er-2.o dedo sobre porción superior de la rótula; 1.er dedo en borde externo, 2.o en borde interno).",
    "execution": "El paciente lleva a cabo una contracción del músculo CUÁDRICEPS del lado a valorar mientras el terapeuta impide el ascenso de la rótula con una compresión en dirección CAUDAL.\n💡 Realizarla bilateral y a distintos grados de flexión (30°, 60° y 90°) para más especificidad.",
    "interpretation": "✅ Dolor agudo en la rodilla → posible afectación de la articulación femoropatelar (condromalacia rotuliana)."
  },
  {
    "id": 40,
    "region": "🦵 RODILLA",
    "num": "57",
    "name": "Test de Lachmann",
    "category": "Integridad LCA",
    "posPatient": "Decúbito dorsal con la rodilla del lado a valorar flexionada unos 20-30°, brazos a lo largo del cuerpo.",
    "posTherapist": "De pie en el mismo lado de la pierna a evaluar, en finta adelante a la altura de las tibias del paciente, orientado hacia este en dirección craneal. Mano superior sobre la porción anterolateral del tercio distal del fémur homolateral. Mano inferior abarca internamente el extremo proximal de la tibia (pulgar en parte anterior, resto de dedos bajo el hueco poplíteo).",
    "execution": "El terapeuta estabiliza el fémur a través de su contacto superior mientras induce de forma pasiva un desplazamiento ANTERIOR de la tibia con la mano inferior.",
    "interpretation": "✅ Desplazamiento anterior anormalmente aumentado de la tibia → posible desgarro del LCA."
  },
  {
    "id": 41,
    "region": "🦵 RODILLA",
    "num": "58",
    "name": "Test del cajón anterior",
    "category": "Integridad LCA",
    "posPatient": "Decúbito dorsal, brazos a lo largo del cuerpo, cadera y rodilla del lado a valorar en flexión, planta del pie homolateral reposando sobre la camilla. Paciente RELAJADO (isquiotibiales y cuádriceps sin tensión).",
    "posTherapist": "Sedestación sobre el dorso del pie del lado a valorar en dirección craneal. Ambas manos abarcando el tercio proximal de la tibia: pulgares sobre la parte anterior en la interlínea articular femorotibial; resto de dedos entrelazados en el hueco poplíteo.",
    "execution": "Tracción anterior de la tibia del lado a valorar generando un desplazamiento anterior de esta con respecto al fémur.\n⚠️ El paciente debe estar completamente relajado para que la musculatura no altere el resultado.",
    "interpretation": "✅ Desplazamiento anterior aumentado de la tibia → posible afectación o rotura del LCA."
  },
  {
    "id": 42,
    "region": "🦵 RODILLA",
    "num": "59",
    "name": "Test del cajón posterior",
    "category": "Integridad LCP",
    "posPatient": "Decúbito dorsal, brazos a lo largo del cuerpo, cadera y rodilla del lado a valorar flexionadas, pie homolateral reposando sobre la camilla.",
    "posTherapist": "Sedestación sobre el dorso del pie del lado a valorar en dirección craneal. Ambas eminencias tenares sobre la parte anterior de los cóndilos tibiales: pulgares a ambos lados de la interlínea articular femorotibial; resto de dedos abrazando la parte posterior de la tibia.",
    "execution": "Empuje de la tibia en dirección POSTERIOR generando un desplazamiento posterior con respecto al fémur, produciendo rotación interna o externa según las estructuras estabilizadoras que se pretendan evaluar.",
    "interpretation": "✅ Desplazamiento posterior aumentado de la tibia → posible afectación del LCP."
  },
  {
    "id": 43,
    "region": "🦶 TOBILLO",
    "num": "60",
    "name": "Lunge test (carga flexión dorsal tobillo)",
    "category": "Movilidad flexión dorsal tobillo",
    "posPatient": "De pie, descalzo. Posición de zancada (lunge) con el pie a evaluar adelante y la rodilla alineada sobre el 2.o dedo del pie.",
    "posTherapist": "De pie observando al paciente de lado o de frente.",
    "execution": "1. El paciente avanza la rodilla hacia delante (movimiento de lunge) intentando que toque la pared sin que el talón se levante del suelo.\n2. Se mide la distancia máxima del pie a la pared (en cm) donde la rodilla aún puede tocarla sin despegar el talón.\n3. Se compara con el lado contralateral.\n💡 Referencia: ≥10 cm se considera rango funcional de flexión dorsal en carga.",
    "interpretation": "✅ Distancia <10 cm o menor que el lado contralateral → restricción de la flexión dorsal en carga (tríceps sural, rigidez articular o bloqueo anterior del astrágalo)."
  },
  {
    "id": 44,
    "region": "💪 HOMBRO",
    "num": "26",
    "name": "Prueba de Aprehensión (crank test) – Labrum",
    "category": "Inestabilidad hombro / Labrum",
    "posPatient": "Decúbito supino sobre la camilla.",
    "posTherapist": "De pie lateral al paciente, a nivel del hombro a evaluar.",
    "execution": "1. Terapeuta lleva el hombro a 90° de abducción.\n2. Flexiona el codo a 90°.\n3. Realiza una rotación externa pasiva progresiva del hombro.\n4. Puede añadir una presión anterior sobre la cabeza del húmero.",
    "interpretation": "✅ Aprehensión (miedo a la luxación) o dolor anterior → inestabilidad glenohumeral anterior o lesión del labrum."
  },
  {
    "id": 45,
    "region": "💪 HOMBRO",
    "num": "27",
    "name": "Test de O'Brien (Labrum)",
    "category": "Inestabilidad hombro / Labrum",
    "posPatient": "De pie o sentado.",
    "posTherapist": "De pie delante o al lado del paciente.",
    "execution": "1. Brazo en flexión de 90° con 10° de aducción horizontal.\n2. FASE A: Rotación interna máxima (pulgar hacia el suelo) → terapeuta presiona hacia abajo.\n3. FASE B: Rotación NEUTRA (palma hacia arriba) → terapeuta presiona hacia abajo.",
    "interpretation": "✅ Dolor/chasquido en fase A (rot. interna) que mejora en fase B (rot. neutra) → lesión del labrum superior (SLAP) o afectación acromioclavicular."
  },
  {
    "id": 46,
    "region": "💪 HOMBRO",
    "num": "28",
    "name": "Test de Hawkins y Kennedy",
    "category": "Pinzamiento subacromial",
    "posPatient": "Sentado con brazos paralelos al tronco y manos sobre muslos, o de pie con miembros a lo largo del cuerpo.",
    "posTherapist": "De pie lateral al paciente (finta doble). Mano anterior abarca la articulación del codo; mano posterior contacta la parte superior del hombro (pulgar sobre acromion, demás dedos sobre extremo externo de clavícula).",
    "execution": "1. Inducir flexión de codo a 90°.\n2. Llevar el brazo a 90° de abducción.\n3. Realizar flexión horizontal de 45°.\n4. Rotación interna de la glenohumeral (mano hacia el suelo).\n5. Punto fijo en parte superior del hombro con mano posterior + elevar el codo con mano anterior.",
    "interpretation": "✅ Dolor agudo en el hombro → posible pinzamiento subacromial (supraespinoso, bíceps, bursa)."
  },
  {
    "id": 47,
    "region": "💪 HOMBRO",
    "num": "29",
    "name": "Test del Neer",
    "category": "Pinzamiento subacromial",
    "posPatient": "Sentado, brazos paralelos al cuerpo, manos sobre muslos (o de pie, brazos a lo largo del cuerpo).",
    "posTherapist": "De pie lateral al paciente (finta doble). Mano posterior contacta la escápula (porción dorsal). Mano anterior abarca el tercio proximal del cúbito homolateral.",
    "execution": "1. Terapeuta orienta la palma de la mano del lado a evaluar hacia el suelo → rotación interna máxima de la glenohumeral.\n2. Manteniendo el codo en extensión → conduce el hombro hacia FLEXIÓN MÁXIMA.",
    "interpretation": "✅ Dolor agudo en el hombro → pinzamiento subacromial (supraespinoso y tendón largo del bíceps)."
  },
  {
    "id": 48,
    "region": "💪 HOMBRO",
    "num": "30",
    "name": "Test de Yocum",
    "category": "Pinzamiento subacromial",
    "posPatient": "Sentado, con el miembro a valorar en aducción anterior: palma de la mano del lado a estudiar contacta la parte superior del hombro contralateral.",
    "posTherapist": "Bipedestación a la espalda del paciente, ligeramente desplazado del lado a valorar (finta adelante). Mano externa sobre el codo homolateral; otra mano contacta dorso de los dedos del paciente sobre el hombro contrario.",
    "execution": "Terapeuta indica al paciente que eleve el codo del lado a valorar hacia el techo, SIN despegar la mano del hombro contralateral, mientras el terapeuta ofrece RESISTENCIA a este movimiento.",
    "interpretation": "✅ Dolor anterior en el hombro → posible afectación subacromial."
  },
  {
    "id": 49,
    "region": "💪 HOMBRO",
    "num": "31",
    "name": "Drop arm test",
    "category": "Valorar supraespinoso",
    "posPatient": "Sentado, brazos paralelos al tronco, manos sobre muslos (o de pie, brazos a lo largo del cuerpo).",
    "posTherapist": "De pie detrás del paciente, ligeramente desviado al lado a valorar (finta doble). Mano externa abarca la muñeca homolateral; otra mano reposa en porción superior de la escápula del mismo lado.",
    "execution": "1. Terapeuta induce pasivamente separación glenohumeral de 90-120° manteniendo el codo en extensión.\n2. Pide al paciente que MANTENGA el brazo en esa postura.\n3. Pasados unos segundos → le pide que lo lleve LENTAMENTE a la posición inicial.\n💡 Fase 1 alternativa: pedir al paciente que haga el gesto activamente.",
    "interpretation": "✅ Incapacidad de mantener o bajar lentamente el brazo → posible disfunción o rotura del supraespinoso."
  },
  {
    "id": 50,
    "region": "💪 HOMBRO",
    "num": "32",
    "name": "Prueba de Jobe",
    "category": "Valorar supraespinoso",
    "posPatient": "Sedestación. Miembro superior del lado a valorar: separación de 90° por la glenohumeral + 30° de aproximación anterior, húmero y antebrazo en ROTACIÓN INTERNA y PRONACIÓN respectivamente.",
    "posTherapist": "Bipedestación detrás del paciente, desplazado al lado a valorar (finta doble). Mano interna sobre región superior del hombro homolateral; otra mano contacta la porción cubital inferior de la articulación radiocubital.",
    "execution": "El paciente ha de MANTENER la posición mientras el terapeuta realiza un EMPUJE hacia el suelo de la muñeca del brazo a valorar con su mano externa.",
    "interpretation": "✅ Dolor o incapacidad de mantener la postura → afectación del tendón del supraespinoso."
  },
  {
    "id": 51,
    "region": "💪 HOMBRO",
    "num": "33",
    "name": "Signo de Hornblower",
    "category": "Valorar infraespinoso / Redondo menor",
    "posPatient": "De pie o sentado.",
    "posTherapist": "Observación.",
    "execution": "Se pide al paciente que se TOQUE LA BOCA con ambas manos.",
    "interpretation": "✅ Eleva el codo por encima del hombro para llegar a la boca → insuficiencia completa de infraespinoso y redondo menor."
  },
  {
    "id": 52,
    "region": "💪 HOMBRO",
    "num": "34",
    "name": "Prueba de Patte",
    "category": "Valorar infraespinoso",
    "posPatient": "Sedestación. Miembro a valorar en ABDUCCIÓN de 90° de la glenohumeral y FLEXIÓN de codo de 90°.",
    "posTherapist": "Bipedestación a la espalda del paciente, ligeramente desplazado al lado a valorar (finta doble). Mano interna contacta la parte superior de la escápula homolateral; mano externa abarca la articulación radiocubital inferior.",
    "execution": "El paciente ha de llevar la mano hacia el terapeuta realizando una ROTACIÓN EXTERNA de la glenohumeral. El terapeuta RESISTE el movimiento a través del contacto de la mano externa.",
    "interpretation": "✅ Dolor posterior en el hombro → posible afectación del tendón del infraespinoso."
  },
  {
    "id": 53,
    "region": "💪 HOMBRO",
    "num": "35",
    "name": "Prueba de Gerber (lift-off / rot. interna)",
    "category": "Valorar subescapular",
    "posPatient": "Sedestación. Miembro a valorar en: extensión + aproximación posterior + rotación interna de la glenohumeral, codo en flexión → la dorso de la mano contacta las apófisis espinosas torácicas.",
    "posTherapist": "Bipedestación a la espalda del paciente (finta doble), ligeramente desplazado al lado a valorar. Mano externa sobre la espina escapular homolateral; otra mano abarca la mano del paciente del mismo lado.",
    "execution": "Terapeuta pide al paciente que realice una fuerza con la mano del lado a valorar en dirección POSTERIOR (separando la mano de la espalda). El terapeuta aplica RESISTENCIA a este movimiento impidiendo que lo lleve a cabo.",
    "interpretation": "✅ Dolor e incapacidad de separar la mano de la espalda → afectación del músculo subescapular."
  },
  {
    "id": 54,
    "region": "💪 HOMBRO",
    "num": "36",
    "name": "Prueba de Yergarson",
    "category": "Bíceps braquial – SLAP",
    "posPatient": "Sentado, miembro superior a valorar en contacto con el tronco, codo en flexión de 90°, palma mirando al suelo (PRONACIÓN del antebrazo).",
    "posTherapist": "Delante del paciente, ligeramente lateralizado del lado a testar (finta doble). Mano externa toma contacto sensitivo a través de la yema de los dedos sobre la CORREDERA BICIPITAL; otra mano abarca la muñeca del mismo lado.",
    "execution": "El terapeuta pide al paciente que realice DOS movimientos SIMULTÁNEAMENTE:\n1. Orientar la palma hacia el techo → SUPINACIÓN del antebrazo.\n2. FLEXIÓN del codo.\nEl terapeuta RESISTE ambos movimientos. El plano de movimiento debe ser paralelo al esternón.",
    "interpretation": "✅ Dolor en el tendón de la porción larga del bíceps → tendinitis o rotura del ligamento transverso (posible luxación del tendón)."
  },
  {
    "id": 55,
    "region": "💪 HOMBRO",
    "num": "37",
    "name": "Prueba de Speed",
    "category": "Bíceps braquial – SLAP",
    "posPatient": "De pie o sentado. Miembro a valorar en FLEXIÓN de 90° de la glenohumeral, codo en EXTENSIÓN, antebrazo en SUPINACIÓN (palma hacia el techo).",
    "posTherapist": "De pie, finta adelante lateralmente al paciente del lado a valorar. Mano posterior sobre el tercio superior del húmero palpando con yemas de dedos la CORREDERA BICIPITAL; mano anterior contacta con el tercio distal del cúbito por cara anterior.",
    "execution": "El paciente ha de FLEXIONAR aún más la articulación glenohumeral llevando la palma hacia el techo. El terapeuta RESISTE el movimiento intentando llevar el brazo hacia el suelo. Tras finalizar la prueba, realizarla en el miembro contralateral.",
    "interpretation": "✅ Dolor o incapacidad de vencer la resistencia → posible afectación del tendón de la porción larga del bíceps braquial."
  },
  {
    "id": 56,
    "region": "🦾 CODO",
    "num": "38",
    "name": "Test de Tinel (codo – túnel cubital)",
    "category": "Síndrome túnel cubital",
    "posPatient": "Codo en ligera flexión o posición neutra.",
    "posTherapist": "Frente al codo del paciente.",
    "execution": "Terapeuta percute con el dedo (o martillo de reflejos) sobre el NERVIO CUBITAL a su paso por el surco epitrocleo-olecraneano (cara interna del codo).",
    "interpretation": "✅ Parestesias irradiadas al 4.º y 5.º dedo → atrapamiento del nervio cubital en el túnel cubital."
  },
  {
    "id": 57,
    "region": "🦾 CODO",
    "num": "39",
    "name": "Test de Mills",
    "category": "Musculatura epicondílea (epicondilitis lateral)",
    "posPatient": "De pie o sentado.",
    "posTherapist": "De pie frente al paciente o a su lado.",
    "execution": "1. Terapeuta palpa el epicóndilo lateral.\n2. Lleva el codo a EXTENSIÓN completa.\n3. Realiza PRONACIÓN del antebrazo.\n4. Realiza FLEXIÓN de muñeca.\n→ Todo de forma pasiva o pidiéndoselo activamente al paciente.",
    "interpretation": "✅ Dolor en el epicóndilo lateral → afectación de la musculatura epicondílea (epicondilitis lateral)."
  },
  {
    "id": 58,
    "region": "🤚 MUÑECA-MANO",
    "num": "40",
    "name": "Test de presión manual (dinamometría)",
    "category": "Musculatura flexora de la mano",
    "posPatient": "Sentado, codo en 90° de flexión, antebrazo en posición neutra, muñeca en posición neutra.",
    "posTherapist": "Entrega el DINAMÓMETRO de mano al paciente; registra el valor.",
    "execution": "1. El paciente agarra el dinamómetro con fuerza máxima.\n2. Se realizan varias mediciones (generalmente 3) con descanso entre ellas.\n3. Se compara el lado dominante con el no dominante y con valores normativos.",
    "interpretation": "✅ Fuerza reducida o dolor → debilidad de la musculatura flexora de la mano."
  },
  {
    "id": 59,
    "region": "🤚 MUÑECA-MANO",
    "num": "41",
    "name": "Signo de Tinel (muñeca – túnel carpiano)",
    "category": "Síndrome del túnel carpiano",
    "posPatient": "Muñeca en posición neutra, mano apoyada con la palma hacia arriba.",
    "posTherapist": "Frente a la muñeca del paciente.",
    "execution": "Terapeuta percute con el dedo índice o martillo de reflejos sobre el LIGAMENTO TRANSVERSO DEL CARPO (retináculo flexor), en la cara palmar de la muñeca, sobre el trayecto del nervio mediano.",
    "interpretation": "✅ Parestesias irradiadas a dedos 1.º-3.º y mitad del 4.º → atrapamiento del nervio mediano en el túnel carpiano."
  },
  {
    "id": 60,
    "region": "🤚 MUÑECA-MANO",
    "num": "42",
    "name": "Signo de Phalen",
    "category": "Síndrome del túnel carpiano",
    "posPatient": "De pie o sentado.",
    "posTherapist": "Observación.",
    "execution": "El paciente mantiene ambas muñecas en FLEXIÓN MÁXIMA durante 60 segundos (dorso de las manos en contacto, codos en flexión, antebrazo vertical), O el terapeuta realiza la flexión pasivamente.",
    "interpretation": "✅ Parestesias en territorio del nervio mediano (dedos 1.º-3.º y mitad del 4.º) durante la maniobra → síndrome del túnel carpiano."
  }
]
;